-- Schema inicial: congelado a partir do que o Hibernate (ddl-auto) gerava ate aqui.
-- Bancos ja existentes recebem baseline nesta versao (spring.flyway.baseline-on-migrate).

CREATE TABLE analytics_event (
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    organizacao_id bigint,
    usuario_id bigint,
    contexto character varying(255),
    evento character varying(255) NOT NULL,
    metadata_json text
);

ALTER TABLE analytics_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE asset (
    publico boolean NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    organizacao_id bigint NOT NULL,
    tamanho_bytes bigint NOT NULL,
    usuario_id bigint,
    dados_base64 text,
    mime_type character varying(255),
    nome_original character varying(255) NOT NULL,
    storage_path character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL
);

ALTER TABLE asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE assinatura (
    fim timestamp(6) without time zone,
    id bigint NOT NULL,
    inicio timestamp(6) without time zone NOT NULL,
    organizacao_id bigint NOT NULL,
    gateway_customer_id character varying(255),
    gateway_subscription_id character varying(255),
    plano character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT assinatura_plano_check CHECK (((plano)::text = ANY ((ARRAY['FREE'::character varying, 'PRO'::character varying, 'MESTRE'::character varying, 'GUILD'::character varying])::text[])))
);

ALTER TABLE assinatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME assinatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE ataque (
    id bigint NOT NULL,
    personagem_id bigint,
    alcance character varying(255),
    critico character varying(255),
    dano character varying(255),
    efeito text,
    nome character varying(255) NOT NULL,
    pericia character varying(255)
);

ALTER TABLE ataque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ataque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE auditoria (
    criado_em timestamp(6) without time zone NOT NULL,
    entidade_id bigint,
    id bigint NOT NULL,
    organizacao_id bigint,
    usuario_id bigint,
    acao character varying(255) NOT NULL,
    campo character varying(255),
    entidade character varying(255),
    ip character varying(255),
    user_agent character varying(255),
    valor_anterior text,
    valor_novo text
);

ALTER TABLE auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE bencao_personagem (
    custo integer,
    id bigint NOT NULL,
    personagem_id bigint NOT NULL,
    custo_tipo character varying(255),
    divindade character varying(255),
    efeito text,
    nome character varying(255) NOT NULL
);

ALTER TABLE bencao_personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bencao_personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE campanha (
    arquivada boolean NOT NULL,
    permitir_homebrew boolean,
    rolagem_oculta_permitida boolean,
    usar_bencoes boolean,
    usar_combate_tatico boolean,
    usar_divindades boolean,
    usar_magia_avancada boolean,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    mestre_id bigint,
    organizacao_id bigint NOT NULL,
    anotacoes text,
    capa_asset_id character varying(255),
    descricao text,
    discord_webhook_url character varying(255),
    nome character varying(255) NOT NULL
);

ALTER TABLE campanha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME campanha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE campanha_membro (
    campanha_id bigint NOT NULL,
    entrou_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    papel character varying(255) NOT NULL,
    CONSTRAINT campanha_membro_papel_check CHECK (((papel)::text = ANY ((ARRAY['MESTRE'::character varying, 'CO_MESTRE'::character varying, 'JOGADOR'::character varying, 'OBSERVADOR'::character varying])::text[])))
);

ALTER TABLE campanha_membro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME campanha_membro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE campanha_personagem (
    adicionado_em timestamp(6) without time zone NOT NULL,
    campanha_id bigint NOT NULL,
    id bigint NOT NULL,
    personagem_id bigint NOT NULL
);

ALTER TABLE campanha_personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME campanha_personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cena (
    ativa boolean NOT NULL,
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    mapa_asset_id bigint,
    fog_json text,
    nome character varying(255) NOT NULL,
    tokens_json text
);

ALTER TABLE cena ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cena_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE classe (
    multiplicador_pe integer NOT NULL,
    multiplicador_pm integer NOT NULL,
    multiplicador_pv integer NOT NULL,
    oficial boolean NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    classe_pai_codigo character varying(255),
    codigo character varying(255) NOT NULL,
    descricao text,
    json_bonus text,
    json_passiva text,
    json_trilhas text,
    nome character varying(255) NOT NULL
);

ALTER TABLE classe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME classe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE combate (
    ativo boolean NOT NULL,
    rodada integer NOT NULL,
    turno_atual integer NOT NULL,
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    mapa_asset_id bigint,
    fog_json text,
    nome character varying(255) NOT NULL
);

ALTER TABLE combate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME combate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE combate_participante (
    iniciativa integer NOT NULL,
    inimigo boolean NOT NULL,
    posx integer,
    posy integer,
    pv_atual integer NOT NULL,
    pv_max integer NOT NULL,
    avatar_asset_id bigint,
    combate_id bigint NOT NULL,
    id bigint NOT NULL,
    personagem_id bigint,
    condicoes text,
    nome character varying(255) NOT NULL
);

ALTER TABLE combate_participante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME combate_participante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE compra (
    valor_pago numeric(12,2),
    comprado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    marketplace_item_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    moeda character varying(255)
);

ALTER TABLE compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE consentimento (
    aceito boolean NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    tipo character varying(255) NOT NULL,
    versao_documento character varying(255)
);

ALTER TABLE consentimento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME consentimento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE convite (
    ativo boolean NOT NULL,
    max_usos integer,
    usos integer NOT NULL,
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    criado_por_usuario_id bigint,
    expira_em timestamp(6) without time zone,
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    papel character varying(255) NOT NULL,
    CONSTRAINT convite_papel_check CHECK (((papel)::text = ANY ((ARRAY['MESTRE'::character varying, 'CO_MESTRE'::character varying, 'JOGADOR'::character varying, 'OBSERVADOR'::character varying])::text[])))
);

ALTER TABLE convite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME convite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE criatura (
    defesa integer NOT NULL,
    nivel integer NOT NULL,
    oficial boolean NOT NULL,
    pe integer NOT NULL,
    pm integer NOT NULL,
    pv integer NOT NULL,
    game_system_id bigint,
    id bigint NOT NULL,
    categoria character varying(255),
    descricao text,
    especie character varying(255),
    imagem_url text,
    nome character varying(255) NOT NULL,
    rank character varying(255),
    tipo character varying(255)
);

ALTER TABLE criatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME criatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE feitico_personagem (
    circulo integer,
    custo_pm integer,
    id bigint NOT NULL,
    personagem_id bigint,
    alcance character varying(255),
    duracao character varying(255),
    efeito text,
    nome character varying(255) NOT NULL
);

ALTER TABLE feitico_personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME feitico_personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE game_system (
    ativo boolean NOT NULL,
    oficial boolean NOT NULL,
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    versao character varying(255) NOT NULL
);

ALTER TABLE game_system ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_system_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE habilidade (
    custo integer NOT NULL,
    nivel_minimo integer NOT NULL,
    oficial boolean NOT NULL,
    valor_atributo_requisito integer NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    atributo_requisito character varying(255),
    classe_codigo character varying(255),
    codigo character varying(255) NOT NULL,
    custo_tipo character varying(255),
    efeito text,
    nome character varying(255) NOT NULL,
    requisito text,
    tipo character varying(255)
);

ALTER TABLE habilidade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME habilidade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE habilidade_personagem (
    custo_custom integer,
    id bigint NOT NULL,
    personagem_id bigint NOT NULL,
    custo_tipo_custom character varying(255),
    efeito_custom text,
    habilidade_codigo character varying(255) NOT NULL,
    nome_custom character varying(255),
    tipo_custom character varying(255)
);

ALTER TABLE habilidade_personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME habilidade_personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE handout (
    asset_id bigint,
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    texto text,
    titulo character varying(255) NOT NULL
);

ALTER TABLE handout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME handout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE item_jogo (
    bonus_defesa integer,
    espacos double precision,
    oficial boolean NOT NULL,
    penalidade integer,
    preco numeric(12,2),
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    alcance character varying(255),
    categoria character varying(255),
    codigo character varying(255) NOT NULL,
    critico character varying(255),
    dano character varying(255),
    efeito text,
    grupo character varying(255),
    moeda character varying(255),
    nome character varying(255) NOT NULL,
    tipo_dano character varying(255)
);

ALTER TABLE item_jogo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_jogo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE item_personagem (
    bonus_defesa integer,
    equipado boolean NOT NULL,
    espacos double precision,
    penalidade integer,
    preco numeric(12,2),
    quantidade integer,
    id bigint NOT NULL,
    personagem_id bigint NOT NULL,
    alcance character varying(255),
    categoria character varying(255),
    critico character varying(255),
    dano character varying(255),
    efeito text,
    item_jogo_codigo character varying(255),
    moeda character varying(255),
    nome character varying(255) NOT NULL,
    tipo_dano character varying(255)
);

ALTER TABLE item_personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE marketplace_item (
    gratuito boolean NOT NULL,
    oficial boolean,
    preco numeric(12,2),
    publicado boolean NOT NULL,
    autor_usuario_id bigint,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    descricao text,
    moeda character varying(255),
    tipo character varying(255),
    titulo character varying(255) NOT NULL
);

ALTER TABLE marketplace_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE mensagem_campanha (
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    usuario_id bigint,
    autor character varying(255),
    texto text NOT NULL
);

ALTER TABLE mensagem_campanha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mensagem_campanha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE notificacao (
    lida boolean NOT NULL,
    criada_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    mensagem text,
    tipo character varying(255),
    titulo character varying(255)
);

ALTER TABLE notificacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notificacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE organizacao (
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone NOT NULL,
    dono_id bigint,
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    plano character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    CONSTRAINT organizacao_plano_check CHECK (((plano)::text = ANY ((ARRAY['FREE'::character varying, 'PRO'::character varying, 'MESTRE'::character varying, 'GUILD'::character varying])::text[])))
);

ALTER TABLE organizacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organizacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE organizacao_membro (
    entrou_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    organizacao_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    papel character varying(255) NOT NULL,
    CONSTRAINT organizacao_membro_papel_check CHECK (((papel)::text = ANY ((ARRAY['DONO'::character varying, 'ADMIN'::character varying, 'MESTRE'::character varying, 'JOGADOR'::character varying, 'OBSERVADOR'::character varying])::text[])))
);

ALTER TABLE organizacao_membro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organizacao_membro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE pericia (
    oficial boolean NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    atributo_base character varying(255) NOT NULL,
    codigo character varying(255) NOT NULL,
    descricao text,
    exemplos text,
    nome character varying(255) NOT NULL
);

ALTER TABLE pericia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pericia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE personagem (
    armadura_fisica integer,
    armadura_magica integer,
    arquivado boolean NOT NULL,
    base_agilidade integer,
    base_carisma integer,
    base_constituicao integer,
    base_destreza integer,
    base_forca integer,
    base_inteligencia integer,
    base_sabedoria integer,
    dinheiro double precision,
    final_agilidade integer,
    final_carisma integer,
    final_constituicao integer,
    final_destreza integer,
    final_forca integer,
    final_inteligencia integer,
    final_sabedoria integer,
    nivel integer NOT NULL,
    pe_atual integer,
    pe_max integer,
    pe_max_manual integer,
    pm_atual integer,
    pm_max integer,
    pm_max_manual integer,
    pv_atual integer,
    pv_max integer,
    pv_max_manual integer,
    xp_atual integer NOT NULL,
    atualizado_em timestamp(6) without time zone,
    avatar_asset_id bigint,
    classe_id bigint,
    classe_secundaria_id bigint,
    criado_em timestamp(6) without time zone NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    organizacao_id bigint NOT NULL,
    raca_id bigint,
    trilha_id bigint,
    trilha_secundaria_id bigint,
    usuario_id bigint,
    anotacoes text,
    aparencia text,
    divindade character varying(255),
    historico text,
    jogador character varying(255),
    json_pericias text,
    json_pericias_custom text,
    json_pericias_outros text,
    nome character varying(255) NOT NULL,
    objetivo text,
    personalidade text,
    ruleset_version character varying(255) NOT NULL,
    share_token character varying(255)
);

ALTER TABLE personagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME personagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE personagem_snapshot (
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    personagem_id bigint NOT NULL,
    json_ficha text NOT NULL,
    motivo character varying(255) NOT NULL
);

ALTER TABLE personagem_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME personagem_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE presenca_sessao (
    id bigint NOT NULL,
    sessao_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    status character varying(255)
);

ALTER TABLE presenca_sessao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME presenca_sessao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE progressao_nivel (
    limite_atributo integer NOT NULL,
    nivel integer NOT NULL,
    xp_necessario integer NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    foco character varying(255),
    recompensa character varying(255)
);

ALTER TABLE progressao_nivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME progressao_nivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE raca (
    oficial boolean NOT NULL,
    pe_base integer NOT NULL,
    pm_base integer NOT NULL,
    pv_base integer NOT NULL,
    game_system_id bigint NOT NULL,
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    descricao text,
    json_habilidades text,
    nome character varying(255) NOT NULL
);

ALTER TABLE raca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME raca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE rolagem (
    critico boolean NOT NULL,
    falha_critica boolean NOT NULL,
    naturald20 integer,
    oculta boolean NOT NULL,
    revelada boolean NOT NULL,
    total integer NOT NULL,
    campanha_id bigint NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    personagem_id bigint,
    usuario_id bigint,
    detalhe character varying(255) NOT NULL,
    expressao character varying(255) NOT NULL,
    rotulo character varying(255)
);

ALTER TABLE rolagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rolagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE sessao (
    campanha_id bigint NOT NULL,
    fim timestamp(6) without time zone,
    id bigint NOT NULL,
    inicio timestamp(6) without time zone,
    descricao text,
    status character varying(255),
    titulo character varying(255) NOT NULL
);

ALTER TABLE sessao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sessao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE template (
    oficial boolean NOT NULL,
    publico boolean NOT NULL,
    autor_usuario_id bigint,
    criado_em timestamp(6) without time zone NOT NULL,
    game_system_id bigint,
    id bigint NOT NULL,
    organizacao_id bigint,
    descricao text,
    json_conteudo text,
    nome character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL
);

ALTER TABLE template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE usuario (
    anonimizado boolean NOT NULL,
    criado_em timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    senha_hash character varying(255)
);

ALTER TABLE usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY analytics_event
    ADD CONSTRAINT analytics_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY asset
    ADD CONSTRAINT asset_pkey PRIMARY KEY (id);

ALTER TABLE ONLY assinatura
    ADD CONSTRAINT assinatura_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ataque
    ADD CONSTRAINT ataque_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);

ALTER TABLE ONLY bencao_personagem
    ADD CONSTRAINT bencao_personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY campanha_membro
    ADD CONSTRAINT campanha_membro_campanha_id_usuario_id_key UNIQUE (campanha_id, usuario_id);

ALTER TABLE ONLY campanha_membro
    ADD CONSTRAINT campanha_membro_pkey PRIMARY KEY (id);

ALTER TABLE ONLY campanha_personagem
    ADD CONSTRAINT campanha_personagem_campanha_id_personagem_id_key UNIQUE (campanha_id, personagem_id);

ALTER TABLE ONLY campanha_personagem
    ADD CONSTRAINT campanha_personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY campanha
    ADD CONSTRAINT campanha_pkey PRIMARY KEY (id);

ALTER TABLE ONLY cena
    ADD CONSTRAINT cena_pkey PRIMARY KEY (id);

ALTER TABLE ONLY classe
    ADD CONSTRAINT classe_pkey PRIMARY KEY (id);

ALTER TABLE ONLY combate_participante
    ADD CONSTRAINT combate_participante_pkey PRIMARY KEY (id);

ALTER TABLE ONLY combate
    ADD CONSTRAINT combate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY compra
    ADD CONSTRAINT compra_pkey PRIMARY KEY (id);

ALTER TABLE ONLY compra
    ADD CONSTRAINT compra_usuario_id_marketplace_item_id_key UNIQUE (usuario_id, marketplace_item_id);

ALTER TABLE ONLY consentimento
    ADD CONSTRAINT consentimento_pkey PRIMARY KEY (id);

ALTER TABLE ONLY convite
    ADD CONSTRAINT convite_codigo_key UNIQUE (codigo);

ALTER TABLE ONLY convite
    ADD CONSTRAINT convite_pkey PRIMARY KEY (id);

ALTER TABLE ONLY criatura
    ADD CONSTRAINT criatura_pkey PRIMARY KEY (id);

ALTER TABLE ONLY feitico_personagem
    ADD CONSTRAINT feitico_personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY game_system
    ADD CONSTRAINT game_system_pkey PRIMARY KEY (id);

ALTER TABLE ONLY habilidade_personagem
    ADD CONSTRAINT habilidade_personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY habilidade
    ADD CONSTRAINT habilidade_pkey PRIMARY KEY (id);

ALTER TABLE ONLY handout
    ADD CONSTRAINT handout_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_jogo
    ADD CONSTRAINT item_jogo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY item_personagem
    ADD CONSTRAINT item_personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY marketplace_item
    ADD CONSTRAINT marketplace_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY mensagem_campanha
    ADD CONSTRAINT mensagem_campanha_pkey PRIMARY KEY (id);

ALTER TABLE ONLY notificacao
    ADD CONSTRAINT notificacao_pkey PRIMARY KEY (id);

ALTER TABLE ONLY organizacao_membro
    ADD CONSTRAINT organizacao_membro_pkey PRIMARY KEY (id);

ALTER TABLE ONLY organizacao
    ADD CONSTRAINT organizacao_pkey PRIMARY KEY (id);

ALTER TABLE ONLY organizacao
    ADD CONSTRAINT organizacao_slug_key UNIQUE (slug);

ALTER TABLE ONLY pericia
    ADD CONSTRAINT pericia_pkey PRIMARY KEY (id);

ALTER TABLE ONLY personagem
    ADD CONSTRAINT personagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY personagem_snapshot
    ADD CONSTRAINT personagem_snapshot_pkey PRIMARY KEY (id);

ALTER TABLE ONLY presenca_sessao
    ADD CONSTRAINT presenca_sessao_pkey PRIMARY KEY (id);

ALTER TABLE ONLY presenca_sessao
    ADD CONSTRAINT presenca_sessao_sessao_id_usuario_id_key UNIQUE (sessao_id, usuario_id);

ALTER TABLE ONLY progressao_nivel
    ADD CONSTRAINT progressao_nivel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY raca
    ADD CONSTRAINT raca_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rolagem
    ADD CONSTRAINT rolagem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sessao
    ADD CONSTRAINT sessao_pkey PRIMARY KEY (id);

ALTER TABLE ONLY template
    ADD CONSTRAINT template_pkey PRIMARY KEY (id);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

